version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
